import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
SEED = 42
BATCH_SIZE = 32
EMBEDDING_DIM = 128
NUM_EPOCHS = 50
LEARNING_RATE = 5e-4
MAX_CODE_LEN = 150
MAX_SUMMARY_LEN = 50
MAX_SAMPLES_TRAIN = 30000
MAX_SAMPLES_VALIDATION = 500
MAX_SAMPLES_TEST = 500
SRC_VOCAB_SIZE = 5000
TGT_VOCAB_SIZE = 3000
ENC_LAYER = 2
DEC_LAYER = 2
N_HEADS = 8
FEED_FWD = 4 * EMBEDDING_DIM
DROPOUT = 0.3